name = "StationarySheath"
uuid = "e1b266e2-8ec9-43c6-803d-76f631a70308"
authors = ["Averil Prost <averilprost33@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GitHubActions = "6b79fd1a-b13a-48ab-b6b0-aaee1fee41df"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ScatteredInterpolation = "3f865c0f-6dca-5f4d-999b-29fe1e7e3c92"

[compat]
DocStringExtensions = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
